on:
    push:
      branches:
      - '*'
    pull_request:
      branches:
      - '*'
jobs:
    test:
      name: Ex3 Linux
      runs-on: 'ubuntu-latest'
      steps:
        - uses: actions/checkout@v2
        - uses: goanpeca/setup-miniconda@v1
          with:
             activate-environment: louis
             environment-file: environment.yml
             auto-activate-base: false
        - name: conda
          shell: bash
          run: |
            conda info
            conda list
        - name: conda
          shell: bash
          run: |
            python -m compileall
