on:
    push:
      branches:
      - '*'
    pull_request:
      branches:
      - '*'
  
  jobs:
    test:
      name: Ex3 Linux
      runs-on: 'ubuntu-latest'
      steps:
        - uses: actions/checkout@v2
        - uses: goanpeca/setup-miniconda@v1
          with:
             activate-environment: louis
             environment-file: environment.yml
             python-version: 3.5
             auto-activate-base: false
        - shell: bash -l {0}
          run: |
            conda info
            conda list
